# Generated by Django 2.2.7 on 2020-09-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
                ('name_p', models.CharField(max_length=400)),
                ('rate', models.IntegerField(default=0)),
                ('zone_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('career', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('type_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.People')),
            ],
        ),
    ]
