# Generated by Django 2.2.7 on 2020-09-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_people_person_place_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='zone_p',
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='type_n',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='rate',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
